apiVersion: api/v1
kind: Deployment
metadata:
  name: dot-api-k8s-deployment
  labels:
    app: dot-api-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dot-api-k8s
    template:
      metadata:
        labels:
          app: dot-api-k8s
      spec:
        containers:
          - name: dot-api-k8s
            image: oyelekerichard/dot_api
            ports:
              - containerPort: 8080